const express = require("express");
const router = express.Router();
const { getAllOrders, getOrderById, getOrdersByCustomerId, createOrder, updateOrder, patchOrder, deleteOrder } = require("../controllers/order.controller");
router.get("/", getAllOrders);
router.get("/customer/:customerId", getOrdersByCustomerId);
router.get("/:id", getOrderById);
router.post("/", createOrder);
router.put("/:id", updateOrder);
router.patch("/:id", patchOrder);
router.delete("/:id", deleteOrder);
module.exports = router;
