const express = require("express");
const router = express.Router();
const authMiddleware = require("../middlewares/auth.middleware");
const { getAllOrders, getOrderById, getOrdersByCustomerId, getMyOrderById, createOrder, updateOrder, patchOrder, deleteOrder } = require("../controllers/order.controller");
router.get("/me/:id", authMiddleware, getMyOrderById);
router.get("/", getAllOrders);
router.get("/customer/:customer_id", getOrdersByCustomerId);
router.get("/:id", getOrderById);
router.post("/", createOrder);
router.put("/:id", updateOrder);
router.patch("/:id", patchOrder);
router.delete("/:id", deleteOrder);
module.exports = router;
