const express = require("express");
const router = express.Router();
const { getAllReviews, getReviewById, getReviewsByProductId, createReview, updateReview, patchReview, deleteReview } = require("../controllers/review.controller");
router.get("/", getAllReviews);
router.get("/product/:productId", getReviewsByProductId);
router.get("/:id", getReviewById);
router.post("/", createReview);
router.put("/:id", updateReview);
router.patch("/:id", patchReview);
router.delete("/:id", deleteReview);
module.exports = router;
