const express = require("express");
const router = express.Router();
const authMiddleware = require("../middlewares/auth.middleware");
const { getAllWishlists, getWishlistById, getWishlistsByCustomerId, getMyWishlist, createWishlist, updateWishlist, deleteWishlist } = require("../controllers/wishlist.controller");
router.get("/me", authMiddleware, getMyWishlist);
router.get("/", getAllWishlists);
router.get("/customer/:customer_id", getWishlistsByCustomerId);
router.get("/:id", getWishlistById);
router.post("/", createWishlist);
router.put("/:id", updateWishlist);
router.delete("/:id", deleteWishlist);
module.exports = router;
